[profile.default]
src = 'contracts/src/'
test = 'contracts/test/'
script = 'contracts/script/'
libs = [ 'contracts/lib/' ]
via_ir = true
#sparse_mode = true
solc = '0.8.28'
evm_version = 'prague'
allow_internal_expect_revert = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = '127.0.0.1:8545'
sepolia = '${SEPOLIA_RPC_URL}'
homestead = '${HOMESTEAD_RPC_URL}'
goerli = '${GOERLI_RPC_URL}'
matic = '${MATIC_RPC_URL}'
mumbai = '${MUMBAI_RPC_URL}'

[etherscan]
sepolia = { key = '${ETHERSCAN_API_KEY}', chain = 11155111 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
