[profile.default]
src = 'contracts/src/'
test = 'contracts/test/'
libs = [ 'contracts/lib/' ]
#via_ir = true
#sparse_mode = true

[rpc_endpoints]
localhost = '127.0.0.1:8545'
homestead = '${HOMESTEAD_RPC_URL}'
goerli = '${GOERLI_RPC_URL}'
matic = '${MATIC_RPC_URL}'
mumbai = '${MUMBAI_RPC_URL}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
